config/routes.rb
Rails.application.routes.draw do
  resources :items, only: [:create, :new, :update, :edit]
  resources :tables
  root 'tables#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :table
end

app/models/item_catalogo.rb
class ItemCatalogo < ApplicationRecord
end

app/models/table.rb
class Table < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  def table
    @table_id = params[:id]
    puts("table id = ", @table_id)
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
    @tables = Table.where(open:true)
    @item_catalogo = ItemCatalogo.all
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)
    puts(item_params)
    table_id = @item.table_id

    respond_to do |format|
      if @item.save
        format.html { redirect_to table_path(table_id), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :price, :quantity, :table_id)
    end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_table, only: %i[ show edit update destroy ]

  # GET /tables or /tables.json
  def index
    @tables = Table.all
  end

  # GET /tables/1 or /tables/1.json
  def show
    table_id = @table.id
    @items = Item.where(table_id: table_id)
  end

  # GET /tables/new
  def new
    @table = Table.new
    @table.open = true
  end

  # GET /tables/1/edit
  def edit
  end

  # POST /tables or /tables.json
  def create
    @table = Table.new(table_params)
    @table.open = true

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: "Table was successfully created." }
        format.json { render :show, status: :created, location: @table }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1 or /tables/1.json
  def update
    puts("Cheguei aqui meu bom = ", @table)
    @table.open = false

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: "Mesa fechada com sucesso!" }
        format.json { render :show, status: :ok, location: @table }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end

    #respond_to do |format|
    #  if @table.update(table_params)
    #    format.html { redirect_to @table, notice: "Table was successfully updated." }
    #    format.json { render :show, status: :ok, location: @table }
    #  else
    #    format.html { render :edit, status: :unprocessable_entity }
    #    format.json { render json: @table.errors, status: :unprocessable_entity }
    #  end
    #end
  end

  # DELETE /tables/1 or /tables/1.json
  def destroy
    @table.destroy
    respond_to do |format|
      format.html { redirect_to tables_url, notice: "Table was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def table_params
      params.require(:table).permit(:number, :open)
    end
    def close_table
      @table.open = false
      @table.save
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController  
end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
  def total_label
    if (is_open())
      return "Sub total"
    end

    return 'Total'
  end

  def current_total
    items = @items
    total = 0
    items.each { | item |
      total += (item.price * item.quantity)
    }

    return total
  end

  def has_items
    return @items.size != 0
  end

  def is_open
    return @table.open
  end

  def close_table_path
    table_id = @table.id
    return "/tables/#{table_id}"
  end

  def open_label(table)
    if table.open
      return "Aberta"
    else
      return "Fechada"
    end
  end

  def quantity_total
    tot = 0
    @items.each { |item|
      tot += item.quantity
    }

    return tot
  end
end

app/views/items/_form.html.erb
<div class="container">
  <%= form_with(model: item) do |form| %>
    <% if item.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

        <ul>
          <% item.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <div class="form-label">
        <%=  form.label :name %>
      </div>
        <%= form.text_field :name %>
    </div>

    <div class="field">
    <div class="form-label">
      <%= form.label :price %>
    </div>
      <%= form.text_field :price %>
    </div>

    <div class="field">
    <div class="form-label">
      <%= form.label :quantity %>
    </div>
      <%= form.number_field :quantity %>
    </div>

    <div class="field">
    <div class="form-label">
      <%= form.label "Mesa" %>
    </div>
      <%= collection_select(:item, :table_id, @tables, :id, :number) %> 
    </div>

    <div class="actions">
      <%= form.submit class: 'btn btn-success', value: 'Adicionar' %>
    </div>
  <% end %>
</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<%= render "layouts/menu" %>

<h1>Items</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Preço</th>
      <th scope="col">Quantidade</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <th scope="row"><%= item.id %></th>
        <td><%= item.name %></td>
        <td>R$ <%= item.price %></td>
        <td><%= item.quantity %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr class="table-success">
      <td><%= total_label %></td>
      <td colspan="2"></td>
      <td ><%= current_total %></td>
    </tr>
  </tfoot>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<%= render "layouts/menu" %>

<h1>Adicionar item</h1>

<%= render 'form', item: @item %>

<%=  link_to 'Voltar', tables_path, :class => "btn btn-warning"%>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @item.quantity %>
</p>

<p>
  <strong>Table:</strong>
  <%= @item.table_id %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-light bg-primary" style="margin-bottom: 20px;">
  <div class="container">
    <a class="navbar-brand" style="color: white;" href="<%= tables_path %>">
      Tables
    </a>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tables</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tables/_form.html.erb
<div class="container">
  <%= form_with(model: table) do |form| %>
    <% if table.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(table.errors.count, "error") %> prohibited this table from being saved:</h2>

        <ul>
          <% table.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :number, 'Número' %>
      <%= form.number_field :number %>
    </div>

    <div class="actions">
      <%= form.submit 'Salvar', class:'btn btn-success'%>
    </div>
  <% end %>
</div>

app/views/tables/edit.html.erb
<h1>Editing Table</h1>

<%= render 'form', table: @table %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

app/views/tables/index.html.erb
<%= render "layouts/menu" %>

<div class="container">
  <h3 class="text-center">Mesas</h3>
  <div>
    <%= link_to 'Adicionar Mesa', new_table_path, :class => "btn btn-primary", :style => "color: white" %>
  </div>
  <div class="row justify-content-md-center" style="margin-top: 10px">
    <% @tables.each do |table| %>
      <div class="card col-md-auto" style="width: 18rem; margin: 12px; min-height:110px;">
        <div class="card-body">
          <h6>Mesa: <%= table.number %></h6>
          <p style="font-size: 14px;"><%= open_label(table) %></p>
          <%= link_to 'Entrar na mesa', table, :class => "btn btn-primary", :style => "color: white" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tables/new.html.erb
<%= render "layouts/menu" %>
<div class="container">
<h1>Nova Mesa</h1>

<%= render 'form', table: @table %>

<%= link_to 'Voltar', tables_path, :class => "btn btn-warning", :style => "color: white" %>
</div>

app/views/tables/show.html.erb
<%= render "layouts/menu" %>

<div class="container">
  <h3 class="text-center">Itens da mesa <%= @table.number %></h3>
  <% if has_items %>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Nome</th>
          <th scope="col">Preço</th>
          <th scope="col">Quantidade</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
          <tr>
            <td><%= item.name %></td>
            <td>R$ <%= item.price %></td>
            <td><%= item.quantity %></td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr class="table-success">
          <td><%= total_label %></td>
          <td>R$ <%= current_total %></td>
          <td><%= quantity_total %></td>
        </tr>
      </tfoot>
    </table>
  <% else %>
    <h3 class="text-center">Nenhum item foi adicionado a essa mesa</h3>
  <% end %>

  <br />

  <% if is_open %>
  <div class="d-flex flex-row justify-content-between">
    <div class="p-2">
    <%= link_to 'Adicionar Item', new_item_path, :class => "btn btn-primary", :style => "color: white" %>
    </div>
    <div class="p-2">
    <%= button_to 'Fechar conta', close_table_path, method: :put, :class => "btn btn-danger", :style => "color: white"  %>
    </div>
  </div>
  <% end %>

  <br />

  <%= link_to 'Voltar', tables_path, :class => "btn btn-warning", :style => "color: white" %>
</div>

app/views/welcome/index.html.erb
<div class="collapse" id="navbarToggleExternalContent">
  <div class="bg-dark p-4">
    <h5 class="text-white h4">Collapsed content</h5>
    <span class="text-muted">Toggleable via the navbar brand.</span>
  </div>
</div>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>

<main>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Album example</h1>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        <p>
          <a href="#" class="btn btn-primary my-2">Main call to action</a>
          <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>
      </div>
    </div>
  </section>
</main>